databases:
  - name: test-app-db
    databaseName: test_app_production
    user: test_app_user
    region: singapore

services:
  - type: web
    name: test-app
    runtime: ruby
    region: singapore
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: starter
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: development:test
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_MAX_THREADS
        value: 5
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
